import { colorModeManager, ColorModeScript, Container, UIProvider } from '@yamada-ui/react'
import { Inter } from 'next/font/google'

import { Header } from '@/components/layouts/Header/Header'

import type { Metadata } from 'next'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorModeScript type="cookie" nonce="testing" />
        <UIProvider colorModeManager={{ ...colorModeManager }.cookieStorage}>
          <Header />
          <Container as="main">{children}</Container>
        </UIProvider>
      </body>
    </html>
  )
}
